# PART 1

In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("Python-Dev-Hemoglobin-Data-Sheet1.csv")
df.head()

,image_name,hbvalues,model,mid_b_mean,mid_g_mean,mid_r_mean,mid_b_median,mid_g_median,mid_r_median,mid_l_mean,...,mid_br_mean,mid_l_median,mid_a_median,mid_br_median,mid_h_mean,mid_s_mean,mid_v_mean,mid_h_median,mid_s_median,mid_v_median
0,image1,9.9,IN2011,49.807024,12.985241,235.497289,45.0,12.0,240.0,128.758904,...,171.903989,129.0,204.0,175.0,174.682041,241.407604,240.891782,176,242.0,240.0
1,image2,12.8,CPH2413,52.194535,78.836233,207.620027,48.0,81.0,212.0,131.390442,...,170.015752,133.0,178.0,173.0,8.421965,199.132372,213.014520,6,198.0,212.5
2,image3,9.4,CPH2413,73.868254,92.552331,211.318028,71.0,94.5,216.0,139.659873,...,162.233389,141.0,174.0,165.0,7.462358,174.399350,216.712522,5,172.0,217.0
3,image4,12.9,IN2011,29.654361,0.164809,246.117047,24.0,0.0,254.0,133.043224,...,183.640993,136.0,208.0,188.0,175.836184,254.835191,251.511541,177,255.0,255.0
4,image5,9.3,SM-A032F,121.105467,119.894385,178.069980,119.5,123.0,181.0,144.987079,...,137.230241,147.0,150.0,139.0,4.632829,93.131766,183.464474,2,88.0,181.5

In [3]:
df.shape

(425, 21)

In [4]:
df['model'].value_counts()

model
SM-A032F            70
CPH2413             60
moto g82 5G         45
motorola edge 40    45
iPhone              45
IN2011              40
Pixel 6 Pro         40
I2203               40
vivo 1917           40
Name: count, dtype: int64

In [5]:
df.isnull().sum()

image_name       0
hbvalues         0
model            0
mid_b_mean       0
mid_g_mean       0
mid_r_mean       0
mid_b_median     0
mid_g_median     0
mid_r_median     0
mid_l_mean       0
mid_a_mean       0
mid_br_mean      0
mid_l_median     0
mid_a_median     0
mid_br_median    0
mid_h_mean       0
mid_s_mean       0
mid_v_mean       0
mid_h_median     0
mid_s_median     0
mid_v_median     0
dtype: int64

In [6]:
# Preprocess the data
X = df.drop(['image_name','hbvalues','model'], axis=1)
y = df['hbvalues']

In [7]:
X.head()

,mid_b_mean,mid_g_mean,mid_r_mean,mid_b_median,mid_g_median,mid_r_median,mid_l_mean,mid_a_mean,mid_br_mean,mid_l_median,mid_a_median,mid_br_median,mid_h_mean,mid_s_mean,mid_v_mean,mid_h_median,mid_s_median,mid_v_median
0,49.807024,12.985241,235.497289,45.0,12.0,240.0,128.758904,204.229714,171.903989,129.0,204.0,175.0,174.682041,241.407604,240.891782,176,242.0,240.0
1,52.194535,78.836233,207.620027,48.0,81.0,212.0,131.390442,178.746410,170.015752,133.0,178.0,173.0,8.421965,199.132372,213.014520,6,198.0,212.5
2,73.868254,92.552331,211.318028,71.0,94.5,216.0,139.659873,174.789434,162.233389,141.0,174.0,165.0,7.462358,174.399350,216.712522,5,172.0,217.0
3,29.654361,0.164809,246.117047,24.0,0.0,254.0,133.043224,207.267783,183.640993,136.0,208.0,188.0,175.836184,254.835191,251.511541,177,255.0,255.0
4,121.105467,119.894385,178.069980,119.5,123.0,181.0,144.987079,151.822994,137.230241,147.0,150.0,139.0,4.632829,93.131766,183.464474,2,88.0,181.5

In [8]:
y.head()

0     9.9
1    12.8
2     9.4
3    12.9
4     9.3
Name: hbvalues, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train.shape ,X_test.shape

((340, 18), (85, 18))

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error ,r2_score
from xgboost import XGBRegressor

In [12]:
# Train a model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test)
mse = mean_squared_error(y_test ,y_pred)
r2 = r2_score(y_test ,y_pred)
print('Mean Squared Error : ',mse)
print("R2 Score : ",r2)

Mean Squared Error :  0.03844210588235191
R2 Score :  0.9938355830871956

In [13]:
xg_model = XGBRegressor(n_estimators=45,max_depth=5,learning_rate=0.5)
xg_model.fit(X_train, y_train)

y_pred = xg_model.predict(X_test)
mse = mean_squared_error(y_test ,y_pred)
r2 = r2_score(y_test ,y_pred)
print('Mean Squared Error : ',mse)
print("R2 Score : ",r2)

Mean Squared Error :  0.07769109934629778
R2 Score :  0.9875417770230805

In [14]:
import pickle

with open('models/rf_model.pickle' ,'wb') as file:
    pickle.dump(rf_model ,file)

with open('models/xg_model.pickle' ,'wb') as file:
    pickle.dump(xg_model ,file)

# PART 2

In [15]:
# Filter data for Phone Model 1
df1 = df[df['model'] == 'SM-A032F']

# Filter data for Phone Model 2
df2 = df[df['model'] == 'CPH2413']

In [16]:
df1.head()

,image_name,hbvalues,model,mid_b_mean,mid_g_mean,mid_r_mean,mid_b_median,mid_g_median,mid_r_median,mid_l_mean,...,mid_br_mean,mid_l_median,mid_a_median,mid_br_median,mid_h_mean,mid_s_mean,mid_v_mean,mid_h_median,mid_s_median,mid_v_median
4,image5,9.3,SM-A032F,121.105467,119.894385,178.069980,119.5,123.0,181.0,144.987079,...,137.230241,147.0,150.0,139.0,4.632829,93.131766,183.464474,2,88.0,181.5
25,image26,9.2,SM-A032F,103.576019,102.981080,148.825547,101.0,105.0,153.0,124.619133,...,135.852730,126.0,147.0,138.0,5.486294,90.867012,154.220041,3,88.0,153.5
40,image41,16.2,SM-A032F,79.698816,55.848162,140.276891,76.5,57.5,145.0,93.150805,...,132.962865,94.0,166.0,135.0,172.256888,156.203355,145.671384,173,153.0,145.0
45,image46,16.2,SM-A032F,80.188249,55.866824,140.293507,77.0,58.0,144.5,93.204517,...,132.674781,94.5,166.0,135.0,172.115825,156.186401,145.688000,173,153.0,145.0
47,image48,13.2,SM-A032F,89.994289,73.179370,142.094651,88.0,76.0,146.0,103.595763,...,132.280009,105.0,159.0,135.0,173.775182,127.030719,147.489145,175,123.0,147.0

In [17]:
df2.head()

,image_name,hbvalues,model,mid_b_mean,mid_g_mean,mid_r_mean,mid_b_median,mid_g_median,mid_r_median,mid_l_mean,...,mid_br_mean,mid_l_median,mid_a_median,mid_br_median,mid_h_mean,mid_s_mean,mid_v_mean,mid_h_median,mid_s_median,mid_v_median
1,image2,12.8,CPH2413,52.194535,78.836233,207.620027,48.0,81.0,212.0,131.390442,...,170.015752,133.0,178.0,173.0,8.421965,199.132372,213.014520,6,198.0,212.5
2,image3,9.4,CPH2413,73.868254,92.552331,211.318028,71.0,94.5,216.0,139.659873,...,162.233389,141.0,174.0,165.0,7.462358,174.399350,216.712522,5,172.0,217.0
8,image9,14.8,CPH2413,42.220338,67.199074,220.222265,38.0,69.0,225.0,132.264376,...,175.966907,133.0,187.0,179.0,7.418459,213.511809,225.616759,5,212.0,226.0
13,image14,9.4,CPH2413,66.692539,85.096935,201.852174,63.5,87.5,206.5,132.094432,...,162.385049,133.5,174.0,165.0,7.430348,179.481666,207.246668,5,177.0,207.0
35,image36,9.3,CPH2413,158.601702,59.688586,152.090271,157.0,61.0,156.0,107.653457,...,92.691913,108.0,180.0,94.0,148.978368,158.410484,158.999513,150,156.5,157.0

In [18]:
df1.to_csv('phone_model1.csv' ,index=False)
df2.to_csv('phone_model2.csv' ,index=False)

In [19]:
model_avg_hb = df1.groupby('model')['hbvalues'].mean().reset_index()

In [20]:
calibration_data = pd.merge(df2, model_avg_hb, on='model', how='left')

In [21]:
X = calibration_data.drop(['hbvalues_x', 'image_name', 'model', 'hbvalues_y'], axis=1)
y = calibration_data['hbvalues_x']

In [22]:
X.head()

,mid_b_mean,mid_g_mean,mid_r_mean,mid_b_median,mid_g_median,mid_r_median,mid_l_mean,mid_a_mean,mid_br_mean,mid_l_median,mid_a_median,mid_br_median,mid_h_mean,mid_s_mean,mid_v_mean,mid_h_median,mid_s_median,mid_v_median
0,52.194535,78.836233,207.620027,48.0,81.0,212.0,131.390442,178.746410,170.015752,133.0,178.0,173.0,8.421965,199.132372,213.014520,6,198.0,212.5
1,73.868254,92.552331,211.318028,71.0,94.5,216.0,139.659873,174.789434,162.233389,141.0,174.0,165.0,7.462358,174.399350,216.712522,5,172.0,217.0
2,42.220338,67.199074,220.222265,38.0,69.0,225.0,132.264376,187.453737,175.966907,133.0,187.0,179.0,7.418459,213.511809,225.616759,5,212.0,226.0
3,66.692539,85.096935,201.852174,63.5,87.5,206.5,132.094432,174.415976,162.385049,133.5,174.0,165.0,7.430348,179.481666,207.246668,5,177.0,207.0
4,158.601702,59.688586,152.090271,157.0,61.0,156.0,107.653457,180.589268,92.691913,108.0,180.0,94.0,148.978368,158.410484,158.999513,150,156.5,157.0

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [27]:
new_data = df2.drop(['hbvalues', 'image_name', 'model'] ,axis=1)
new_data_y = df2['hbvalues']

new_predictions = rf_model.predict(new_data)
print("Predicted Hemoglobin Values for New Model:", new_predictions)

Predicted Hemoglobin Values for New Model: [12.859  9.473 14.8    9.4    9.298  9.364 12.808 13.6    9.473  9.302
  9.364 17.     9.437 14.8   13.592 17.    12.9   12.847  9.469  9.589
  9.303  9.4   14.8   12.9   14.8    9.818 17.     9.4    9.364  9.469
  9.703 12.878  9.298 12.896  9.475  9.627  9.469  9.563  9.666 12.821
 17.    17.     9.4    9.364 13.624  9.298  9.469  9.469 13.6    9.473
 12.899  9.708 12.842  9.474 13.6    9.438  9.751 14.8    9.827  9.364]

In [28]:
r2 = r2_score(new_data_y ,new_predictions)
mse = mean_squared_error(new_data_y ,new_predictions)

print("MSE : ",mse)
print("R2 score : ",r2)

MSE :  0.017480216666665323
R2 score :  0.9974172468705111